//go:build go1.22

// Package venueapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package venueapi

import (
	"bytes"
	"compress/flate"
	"encoding/base64"
	"errors"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for HealthResponseStatus.
const (
	Ok HealthResponseStatus = "ok"
)

// Valid indicates whether the value is a known member of the HealthResponseStatus enum.
func (e HealthResponseStatus) Valid() bool {
	switch e {
	case Ok:
		return true
	default:
		return false
	}
}

// Defines values for MoneyCurrency.
const (
	MoneyCurrencyRUB MoneyCurrency = "RUB"
)

// Valid indicates whether the value is a known member of the MoneyCurrency enum.
func (e MoneyCurrency) Valid() bool {
	switch e {
	case MoneyCurrencyRUB:
		return true
	default:
		return false
	}
}

// Defines values for VenueCommandStatus.
const (
	VenueCommandStatusAccepted   VenueCommandStatus = "accepted"
	VenueCommandStatusDelivered  VenueCommandStatus = "delivered"
	VenueCommandStatusDelivering VenueCommandStatus = "delivering"
	VenueCommandStatusPreparing  VenueCommandStatus = "preparing"
	VenueCommandStatusReady      VenueCommandStatus = "ready"
	VenueCommandStatusRejected   VenueCommandStatus = "rejected"
)

// Valid indicates whether the value is a known member of the VenueCommandStatus enum.
func (e VenueCommandStatus) Valid() bool {
	switch e {
	case VenueCommandStatusAccepted:
		return true
	case VenueCommandStatusDelivered:
		return true
	case VenueCommandStatusDelivering:
		return true
	case VenueCommandStatusPreparing:
		return true
	case VenueCommandStatusReady:
		return true
	case VenueCommandStatusRejected:
		return true
	default:
		return false
	}
}

// Defines values for VenueMenuCurrency.
const (
	VenueMenuCurrencyRUB VenueMenuCurrency = "RUB"
)

// Valid indicates whether the value is a known member of the VenueMenuCurrency enum.
func (e VenueMenuCurrency) Valid() bool {
	switch e {
	case VenueMenuCurrencyRUB:
		return true
	default:
		return false
	}
}

// Defines values for VenueOrderStatus.
const (
	VenueOrderStatusAccepted            VenueOrderStatus = "accepted"
	VenueOrderStatusCancelled           VenueOrderStatus = "cancelled"
	VenueOrderStatusDelivered           VenueOrderStatus = "delivered"
	VenueOrderStatusDelivering          VenueOrderStatus = "delivering"
	VenueOrderStatusPendingConfirmation VenueOrderStatus = "pending_confirmation"
	VenueOrderStatusPreparing           VenueOrderStatus = "preparing"
	VenueOrderStatusReady               VenueOrderStatus = "ready"
	VenueOrderStatusRejected            VenueOrderStatus = "rejected"
)

// Valid indicates whether the value is a known member of the VenueOrderStatus enum.
func (e VenueOrderStatus) Valid() bool {
	switch e {
	case VenueOrderStatusAccepted:
		return true
	case VenueOrderStatusCancelled:
		return true
	case VenueOrderStatusDelivered:
		return true
	case VenueOrderStatusDelivering:
		return true
	case VenueOrderStatusPendingConfirmation:
		return true
	case VenueOrderStatusPreparing:
		return true
	case VenueOrderStatusReady:
		return true
	case VenueOrderStatusRejected:
		return true
	default:
		return false
	}
}

// HealthResponse defines model for HealthResponse.
type HealthResponse struct {
	// Service Example: demo-venue
	Service string               `json:"service"`
	Status  HealthResponseStatus `json:"status"`

	// Version Example: 0.1.0
	Version *string `json:"version,omitempty"`
}

// HealthResponseStatus defines model for HealthResponse.Status.
type HealthResponseStatus string

// Money defines model for Money.
type Money struct {
	// Amount Сумма в копейках.
	Amount   int64         `json:"amount"`
	Currency MoneyCurrency `json:"currency"`
}

// MoneyCurrency defines model for Money.Currency.
type MoneyCurrency string

// ProblemDetails defines model for ProblemDetails.
type ProblemDetails struct {
	Code    string                  `json:"code"`
	Details *map[string]interface{} `json:"details,omitempty"`
	Message string                  `json:"message"`
}

// UpdateVenueOrderStatusRequest defines model for UpdateVenueOrderStatusRequest.
type UpdateVenueOrderStatusRequest struct {
	// Reason Допустима только при status=rejected.
	Reason *string `json:"reason,omitempty"`

	// Status Статусы, которые оператор demo-заведения может отправить в platform.
	Status VenueCommandStatus `json:"status"`
}

// VenueCommandStatus Статусы, которые оператор demo-заведения может отправить в platform.
type VenueCommandStatus string

// VenueMenu defines model for VenueMenu.
type VenueMenu struct {
	Categories  []VenueMenuCategory `json:"categories"`
	Currency    VenueMenuCurrency   `json:"currency"`
	MenuVersion int64               `json:"menuVersion"`
	UpdatedAt   time.Time           `json:"updatedAt"`

	// VenueExternalId Example: demo-pizza-1
	VenueExternalId string `json:"venueExternalId"`
}

// VenueMenuCurrency defines model for VenueMenu.Currency.
type VenueMenuCurrency string

// VenueMenuCategory defines model for VenueMenuCategory.
type VenueMenuCategory struct {
	ExternalCategoryId string          `json:"externalCategoryId"`
	Items              []VenueMenuItem `json:"items"`
	Name               string          `json:"name"`
	SortOrder          *int32          `json:"sortOrder,omitempty"`
}

// VenueMenuItem defines model for VenueMenuItem.
type VenueMenuItem struct {
	Available      bool    `json:"available"`
	Description    *string `json:"description,omitempty"`
	ExternalItemId string  `json:"externalItemId"`
	Name           string  `json:"name"`
	Price          Money   `json:"price"`
	SortOrder      *int32  `json:"sortOrder,omitempty"`
}

// VenueOrder defines model for VenueOrder.
type VenueOrder struct {
	CreatedAt       time.Time          `json:"createdAt"`
	Items           []VenueOrderItem   `json:"items"`
	PlatformOrderId openapi_types.UUID `json:"platformOrderId"`
	RejectionReason *string            `json:"rejectionReason,omitempty"`
	Status          VenueOrderStatus   `json:"status"`
	Total           Money              `json:"total"`
	UpdatedAt       time.Time          `json:"updatedAt"`
	VenueOrderId    string             `json:"venueOrderId"`
}

// VenueOrderItem defines model for VenueOrderItem.
type VenueOrderItem struct {
	ExternalItemId string `json:"externalItemId"`
	Name           string `json:"name"`
	Quantity       int32  `json:"quantity"`
	UnitPrice      Money  `json:"unitPrice"`
}

// VenueOrderPage defines model for VenueOrderPage.
type VenueOrderPage struct {
	Items []VenueOrder `json:"items"`

	// NextCursor Cursor следующей страницы; `null`, если данных больше нет.
	NextCursor *string `json:"nextCursor,omitempty"`
}

// VenueOrderStatus defines model for VenueOrderStatus.
type VenueOrderStatus string

// Cursor defines model for Cursor.
type Cursor = string

// Limit defines model for Limit.
type Limit = int32

// OrderStatus defines model for OrderStatus.
type OrderStatus = VenueOrderStatus

// VenueOrderId defines model for VenueOrderId.
type VenueOrderId = string

// BadRequest defines model for BadRequest.
type BadRequest = ProblemDetails

// InternalServerError defines model for InternalServerError.
type InternalServerError = ProblemDetails

// NotFound defines model for NotFound.
type NotFound = ProblemDetails

// ListLocalOrdersParams defines parameters for ListLocalOrders.
type ListLocalOrdersParams struct {
	Status *OrderStatus `form:"status,omitempty" json:"status,omitempty"`
	Limit  *Limit       `form:"limit,omitempty" json:"limit,omitempty"`

	// Cursor Непрозрачный cursor предыдущего ответа, привязанный к фильтру status.
	Cursor *Cursor `form:"cursor,omitempty" json:"cursor,omitempty"`
}

// UpdateLocalOrderStatusJSONRequestBody defines body for UpdateLocalOrderStatus for application/json ContentType.
type UpdateLocalOrderStatusJSONRequestBody = UpdateVenueOrderStatusRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// GetVenueHealth Проверить готовность demo-заведения
	// (GET /v1/health)
	GetVenueHealth(w http.ResponseWriter, r *http.Request)
	// GetLocalMenu Получить локальный снимок меню
	// (GET /v1/menu)
	GetLocalMenu(w http.ResponseWriter, r *http.Request)
	// ListLocalOrders Получить локальные заказы
	// (GET /v1/orders)
	ListLocalOrders(w http.ResponseWriter, r *http.Request, params ListLocalOrdersParams)
	// GetLocalOrder Получить локальный заказ
	// (GET /v1/orders/{venueOrderId})
	GetLocalOrder(w http.ResponseWriter, r *http.Request, venueOrderId VenueOrderId)
	// UpdateLocalOrderStatus Смоделировать смену статуса заказа
	// (POST /v1/orders/{venueOrderId}/status)
	UpdateLocalOrderStatus(w http.ResponseWriter, r *http.Request, venueOrderId VenueOrderId)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetVenueHealth operation middleware
func (siw *ServerInterfaceWrapper) GetVenueHealth(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetVenueHealth(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetLocalMenu operation middleware
func (siw *ServerInterfaceWrapper) GetLocalMenu(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetLocalMenu(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListLocalOrders operation middleware
func (siw *ServerInterfaceWrapper) ListLocalOrders(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params ListLocalOrdersParams

	// ------------- Optional query parameter "status" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "status", r.URL.Query(), &params.Status, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "status"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "status", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: "int32"})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "limit"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "cursor" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "cursor", r.URL.Query(), &params.Cursor, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "cursor"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "cursor", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListLocalOrders(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetLocalOrder operation middleware
func (siw *ServerInterfaceWrapper) GetLocalOrder(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "venueOrderId" -------------
	var venueOrderId VenueOrderId

	err = runtime.BindStyledParameterWithOptions("simple", "venueOrderId", r.PathValue("venueOrderId"), &venueOrderId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "venueOrderId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetLocalOrder(w, r, venueOrderId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateLocalOrderStatus operation middleware
func (siw *ServerInterfaceWrapper) UpdateLocalOrderStatus(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "venueOrderId" -------------
	var venueOrderId VenueOrderId

	err = runtime.BindStyledParameterWithOptions("simple", "venueOrderId", r.PathValue("venueOrderId"), &venueOrderId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "venueOrderId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateLocalOrderStatus(w, r, venueOrderId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of [http.ServeMux].
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	http.Handler
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/v1/health", wrapper.GetVenueHealth)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/v1/menu", wrapper.GetLocalMenu)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/v1/orders", wrapper.ListLocalOrders)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/v1/orders/{venueOrderId}", wrapper.GetLocalOrder)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/v1/orders/{venueOrderId}/status", wrapper.UpdateLocalOrderStatus)

	return m
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"xFrdbhvHFX6VxbQXLbAiKccpEga9SJw0NeA0gtPkJjTKNTmWNubO0rtDwYohQCTjOIHSCA1yUbRogjxA",
	"AZoWK+qPeoUzr9AnKc6Z2V8ORdFxVF8Y4nJ25vx85zs/wyesFQbdUHAhY1Z/wrpe5AVc8og+3epFcRjh",
	"X20etyK/K/1QsDqDf8EELtQezOBI7cFIPYNztQ/HTotecOi7CRyqfThUQ/U1TOAFzByYqQGMYaIGMHL1",
	"oimM1QEcwQjOzRZw4qgvYAqn6hs1UHtq6MTSk724wlzm4+GPejzaYS4TXsBZnekjmcvi1hYPPBQ28MUd",
	"LjblFquvu0zudHFdLCNfbLLdXZfd8QNf4kLbfh36Mr9dmz/weh3J6jdqLnsQRoEnWZ35Qr52g7ks8B77",
	"QS9g9fVazcWjzaf0YF9IvskjOvnDqM2jj0ifRedrbQsC/DriD1id/aqa+aqqv42rn3DR4/lt8Zjs4e12",
	"ek7Xk1vZMdv5JS6L+KOeH/E2q8uoxwvG9B6nxrzxhrvEuLu4VdwNRcxJw3e89l3+qMdjsncrFJIL+tPr",
	"djt+y0NAVT+LEVVPrqjxRhTe7/DgXS49vxPrMy3wPIGZ2iMYnqhBgi0EGuFW9dmuy24LySPhdT7i0TaP",
	"3osiDfbrEvM7OFdDBDlMCP4H6gBj5CuYwnM4gZHT5kG4pvowUXswhqnqwwjF/lMo/xD2RPs6Zf0nzFAk",
	"DEtjTBRb9dVQ7am+A+cwwf9GcAyHqA7h0OyPx/+Rex25dddgg8Rtt33c3etsRGGXR9JHyDzwOjF3WTf3",
	"6AmLebTtt+gt/tgLuh3EHBmHYMzmcOgmYYRvCIzHT1n4kN2zLNzmUexrY2V71yrrlRqzcUcWKJ/mQtXI",
	"l+0f3v+MtyTu/0Eo+M6K+npB2NM+LXnhJzWEMziDkQNjByEOFzCBY/SMeooMmaen390s0ZP5l2Op2jxL",
	"ucioERetnbzx7n78jsV6JXsYsXM72AxSAttqlmmFbYLBnBvby7bTvDYnTcDj2Nu07VlSjk7O1ts0+7jb",
	"9iQvM3KO/1ZQNOKeCeESBL5Hp6uh6qsBTAkKagAzissTzLGUVU3O/H3EUTbermgkJMT9ugFBjshFr9Px",
	"7iP4C4ayBdTSdHQrDAJPtHMJyRI1NgNa3rbFwABGakAm2HcpCtACak/tIwdRSFBRQg81hxLxj7EkIaqd",
	"ItGewQz+g8WIrkvQbiNi2YH6BsOr2/EkhhPaLgkDr9XiXcl1xtSmZeg53vXITvjYa2M2b/OOv83NQ/OB",
	"t60MRFp/wEVv1VjwJN8MI/PJlzy4mnvwqFv63R083wjkRZG3s1r8YziI3icZg87TzyX1kMt6FDDtt2Xh",
	"XXy2Jv3AyutE+O891nlbVzellND1P//cW1svIv4KpUsRpeVziqrmjOTm/ZBXaSHAC/ZfzeXcCJS8rg2w",
	"kp5uhpTVIHNb8sAGF11QlqSoLZUiDiNJLFkosW0VtqWOznvKYhMjVKLqpZ4gtVZMz9ueb8gyzRr3w7DD",
	"PcHKlVPBLjco+y6l2kQjFO2lPGxxyY3acpd0I1NkXYYHXc/8Eg406qbO0+K4OXMvdGQqxyr0GfFVyecl",
	"Ike3WCZ0Al/c1m+uz8dRkm9yfVsqVa/nt20C6STkh+JuWi6U0/yrTOyFPtNlMpRe58p4eVmyz9njZxN6",
	"1vCWre1m1bx2bqKemwPKleg98/jLcft1R/2jniekL3fK+bs43XjzzaXJXPhyYwUGuSILpOLlT7jc+Bum",
	"oF/B+C8b2daEyB/LRZMz/dxRfTilAdlQfUvjsWMHC3oqQbE8/VLtv+U0MXSbroNtNpzC1IHDZE6mnjrw",
	"XFf96ivdeU/UACvVJeFeMvqS/FgaVyXFYJeLti82/9IKxQMfAaNLop9dHGMpJVq807EWyii7Lx6Elpbg",
	"HzCDc2O+k6Sgx1KfphUwo+mjZZjizPcFFQd+ypYkE6Oh6tP0Y6IGqq+nNLkD1D6cNQS14+dqQA35Oe0x",
	"gzMH/TambabUcuBbx9S9jdWQ2g/Vd97euI179knYcSpyUVpXNzf0txmXnjkwbohm2OXC6/qVHS/oNOu4",
	"7BwbwSE8R9zAiTkIzlBL9S12N81q14uk4FF1e72KpW3TddQz7H60mg5M4Ui/kJimIUgNtMMRiklLihuF",
	"CJg1vo3R0iTV863VqTpYsDWhP+nq0C8zeG56uHOYVRqiIeDf1NANMApmpJLWZmBmT4eJumrPqEtGvYBT",
	"2vcLbAbhTO1XHPgBzWNMqfZhbDQu9NGqTzL09cTamHvSEFy0u6EvZLy4sTxERR0zHx+TB0/QFJPEpzPa",
	"dqYOkjemDpzm52va/Q2RAobUot1GyTvGQkgDaqAPKHin0sCYlL6kzugD7nXuhj3JnXd5EDoU3WgglhuA",
	"manXrssMnlidvVapVV7DKPbkFnEAenmLZnn4aZPbplR/V324MLY80s6gqHk3bD3kkXMLCTXmjt6mtcVb",
	"D60mOEZTTmEEL/CjGXhgkB0j0SF7E/NgrmTvc0k66TEjK02hb9Rqr2xWWhpk2malBQJ5occTMNYT0V4Q",
	"eNj2Mfgxhw8zdEjXJgqrbxbBDH3rbcZIx0bne7h/Es2LnfMdzOAIxhRdXyexnhIDRrQNiw7FCoL2GZ6f",
	"TaetDPojzaBMTO8hJeLOpzBtiHLso+OT06lEK1C0nT/UXw0VEGFqWj2hiWiRQo8LBNoQ6hl9miBrbXz8",
	"Z2eOAnXMzCHrTtjyOjSg+QVxlU2Blo7fYYYGNVbDeH1dy2HbPpW3arvsKEOSgnao8wAC8nR+6l8weSJD",
	"BkZSI8MiJYR4RTSmPGaZ71lBp/GFH86QeCgHn+vckVwznpmVp4RlOGqI5vvvFSFQSF4VRyccmw2wjFnL",
	"uDl9nuSGhkhygBYJywJT3akvNeSnlvwwNdXDi2xhxVlIphRApTtYGGGWfsh3Yi7X4IKoc0qPv9RJ4wJm",
	"TvM3aUPjOvmu6LdNHUP51IsVxgUZ/wAO4QQmbzVE/pI3d39rublt6p4Ka9iR08zqYjxo3vGkVj4JN4SZ",
	"ZtPFEubAZ2S9K1TPtki+48c6lD/UoHQLt92f2uMnW1Itdr9Ll+tb5issNL3C7r1fml2y5siatfIWxBqs",
	"BHzsOQoVBjLPzaswT+4S+DrJalJgkmUcVX2Sj4XdxZRVpOKROpjng7yhRk6x9qNwosyIGS3lr6TXSKx7",
	"ZitdFyYn3YuuCujCzwSuCX5XvFzObKFRdnM5ZNJb8etNiDlJV0NYNRu8dcPYhrQf0qssTd/WDtZkGsxw",
	"1LyZDJP1BmrfwXZJPUWkVUzpT2kccwby6siBsdrXWQbOdZFFlZoloyLnOiZprlE1fkaccaiG+UszBH3p",
	"XpKKs1OMyon6m0ONHqr3FEYNQXnjRPVz3Vu+I5wrSStOM5k2NLXwR7lGrlnVXzZdp5lMIprOf/e+b4hm",
	"VT/QKYkKSezv8ybChU7TeKeZVrOUbw9NWT6Ei6wnSZVuiEvxYRrVtADWhsas5zpJ+2Z+nJLcTlIB8xwr",
	"ViKOkS5vyZgw1lWRRqYt3+nr6IwfPkoGnD+bJYjL3wnbO6+MIC6/Ot8tzq1k1OO7/ze22rCAvxRCxOoj",
	"t4ThIxjlcZ6083Pgfsm8ujJJ3qy9ed0/yjos/nhBB4gmOWSCGRyWJkGvksx/so1TiNZV30TkcG4QlUvk",
	"Nn7f1T/+SULpannNzBMvae17UYfV2ZaU3Xq12sEI3gpjWX+j9sY6haCRY+7AHws9xcg6bLLNRku/MUt/",
	"JWhGC1jELlFtkptOE8vlf4mhU9Jidc1p2qq793b/FwAA//8=",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
