//go:build go1.22

// Package platformapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package platformapi

import (
	"bytes"
	"compress/flate"
	"encoding/base64"
	"errors"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for HealthResponseStatus.
const (
	Ok HealthResponseStatus = "ok"
)

// Valid indicates whether the value is a known member of the HealthResponseStatus enum.
func (e HealthResponseStatus) Valid() bool {
	switch e {
	case Ok:
		return true
	default:
		return false
	}
}

// Defines values for MenuCurrency.
const (
	MenuCurrencyRUB MenuCurrency = "RUB"
)

// Valid indicates whether the value is a known member of the MenuCurrency enum.
func (e MenuCurrency) Valid() bool {
	switch e {
	case MenuCurrencyRUB:
		return true
	default:
		return false
	}
}

// Defines values for MoneyCurrency.
const (
	MoneyCurrencyRUB MoneyCurrency = "RUB"
)

// Valid indicates whether the value is a known member of the MoneyCurrency enum.
func (e MoneyCurrency) Valid() bool {
	switch e {
	case MoneyCurrencyRUB:
		return true
	default:
		return false
	}
}

// Defines values for OrderEventType.
const (
	OrderEventTypeAccepted      OrderEventType = "accepted"
	OrderEventTypeCancelled     OrderEventType = "cancelled"
	OrderEventTypeCreated       OrderEventType = "created"
	OrderEventTypeRejected      OrderEventType = "rejected"
	OrderEventTypeStatusChanged OrderEventType = "status_changed"
)

// Valid indicates whether the value is a known member of the OrderEventType enum.
func (e OrderEventType) Valid() bool {
	switch e {
	case OrderEventTypeAccepted:
		return true
	case OrderEventTypeCancelled:
		return true
	case OrderEventTypeCreated:
		return true
	case OrderEventTypeRejected:
		return true
	case OrderEventTypeStatusChanged:
		return true
	default:
		return false
	}
}

// Defines values for OrderStatus.
const (
	OrderStatusAccepted            OrderStatus = "accepted"
	OrderStatusCancelled           OrderStatus = "cancelled"
	OrderStatusDelivered           OrderStatus = "delivered"
	OrderStatusDelivering          OrderStatus = "delivering"
	OrderStatusPendingConfirmation OrderStatus = "pending_confirmation"
	OrderStatusPreparing           OrderStatus = "preparing"
	OrderStatusReady               OrderStatus = "ready"
	OrderStatusRejected            OrderStatus = "rejected"
)

// Valid indicates whether the value is a known member of the OrderStatus enum.
func (e OrderStatus) Valid() bool {
	switch e {
	case OrderStatusAccepted:
		return true
	case OrderStatusCancelled:
		return true
	case OrderStatusDelivered:
		return true
	case OrderStatusDelivering:
		return true
	case OrderStatusPendingConfirmation:
		return true
	case OrderStatusPreparing:
		return true
	case OrderStatusReady:
		return true
	case OrderStatusRejected:
		return true
	default:
		return false
	}
}

// Defines values for OrderStatusChangeSource.
const (
	OrderStatusChangeSourceCustomer OrderStatusChangeSource = "customer"
	OrderStatusChangeSourcePlatform OrderStatusChangeSource = "platform"
	OrderStatusChangeSourceVenue    OrderStatusChangeSource = "venue"
)

// Valid indicates whether the value is a known member of the OrderStatusChangeSource enum.
func (e OrderStatusChangeSource) Valid() bool {
	switch e {
	case OrderStatusChangeSourceCustomer:
		return true
	case OrderStatusChangeSourcePlatform:
		return true
	case OrderStatusChangeSourceVenue:
		return true
	default:
		return false
	}
}

// Defines values for RejectOrderRequestReason.
const (
	Other          RejectOrderRequestReason = "other"
	OutOfStock     RejectOrderRequestReason = "out_of_stock"
	TechnicalIssue RejectOrderRequestReason = "technical_issue"
	VenueClosed    RejectOrderRequestReason = "venue_closed"
)

// Valid indicates whether the value is a known member of the RejectOrderRequestReason enum.
func (e RejectOrderRequestReason) Valid() bool {
	switch e {
	case Other:
		return true
	case OutOfStock:
		return true
	case TechnicalIssue:
		return true
	case VenueClosed:
		return true
	default:
		return false
	}
}

// Defines values for UpdateOrderStatusRequestStatus.
const (
	UpdateOrderStatusRequestStatusDelivered  UpdateOrderStatusRequestStatus = "delivered"
	UpdateOrderStatusRequestStatusDelivering UpdateOrderStatusRequestStatus = "delivering"
	UpdateOrderStatusRequestStatusPreparing  UpdateOrderStatusRequestStatus = "preparing"
	UpdateOrderStatusRequestStatusReady      UpdateOrderStatusRequestStatus = "ready"
)

// Valid indicates whether the value is a known member of the UpdateOrderStatusRequestStatus enum.
func (e UpdateOrderStatusRequestStatus) Valid() bool {
	switch e {
	case UpdateOrderStatusRequestStatusDelivered:
		return true
	case UpdateOrderStatusRequestStatusDelivering:
		return true
	case UpdateOrderStatusRequestStatusPreparing:
		return true
	case UpdateOrderStatusRequestStatusReady:
		return true
	default:
		return false
	}
}

// Defines values for VenueKind.
const (
	Cafe       VenueKind = "cafe"
	Restaurant VenueKind = "restaurant"
	Store      VenueKind = "store"
)

// Valid indicates whether the value is a known member of the VenueKind enum.
func (e VenueKind) Valid() bool {
	switch e {
	case Cafe:
		return true
	case Restaurant:
		return true
	case Store:
		return true
	default:
		return false
	}
}

// Defines values for VenueStatus.
const (
	Active    VenueStatus = "active"
	Suspended VenueStatus = "suspended"
)

// Valid indicates whether the value is a known member of the VenueStatus enum.
func (e VenueStatus) Valid() bool {
	switch e {
	case Active:
		return true
	case Suspended:
		return true
	default:
		return false
	}
}

// Defines values for PartnerOrderStatus.
const (
	PartnerOrderStatusAccepted            PartnerOrderStatus = "accepted"
	PartnerOrderStatusCancelled           PartnerOrderStatus = "cancelled"
	PartnerOrderStatusDelivered           PartnerOrderStatus = "delivered"
	PartnerOrderStatusDelivering          PartnerOrderStatus = "delivering"
	PartnerOrderStatusPendingConfirmation PartnerOrderStatus = "pending_confirmation"
	PartnerOrderStatusPreparing           PartnerOrderStatus = "preparing"
	PartnerOrderStatusReady               PartnerOrderStatus = "ready"
	PartnerOrderStatusRejected            PartnerOrderStatus = "rejected"
)

// Valid indicates whether the value is a known member of the PartnerOrderStatus enum.
func (e PartnerOrderStatus) Valid() bool {
	switch e {
	case PartnerOrderStatusAccepted:
		return true
	case PartnerOrderStatusCancelled:
		return true
	case PartnerOrderStatusDelivered:
		return true
	case PartnerOrderStatusDelivering:
		return true
	case PartnerOrderStatusPendingConfirmation:
		return true
	case PartnerOrderStatusPreparing:
		return true
	case PartnerOrderStatusReady:
		return true
	case PartnerOrderStatusRejected:
		return true
	default:
		return false
	}
}

// Defines values for ListPartnerOrdersParamsStatus.
const (
	ListPartnerOrdersParamsStatusAccepted            ListPartnerOrdersParamsStatus = "accepted"
	ListPartnerOrdersParamsStatusCancelled           ListPartnerOrdersParamsStatus = "cancelled"
	ListPartnerOrdersParamsStatusDelivered           ListPartnerOrdersParamsStatus = "delivered"
	ListPartnerOrdersParamsStatusDelivering          ListPartnerOrdersParamsStatus = "delivering"
	ListPartnerOrdersParamsStatusPendingConfirmation ListPartnerOrdersParamsStatus = "pending_confirmation"
	ListPartnerOrdersParamsStatusPreparing           ListPartnerOrdersParamsStatus = "preparing"
	ListPartnerOrdersParamsStatusReady               ListPartnerOrdersParamsStatus = "ready"
	ListPartnerOrdersParamsStatusRejected            ListPartnerOrdersParamsStatus = "rejected"
)

// Valid indicates whether the value is a known member of the ListPartnerOrdersParamsStatus enum.
func (e ListPartnerOrdersParamsStatus) Valid() bool {
	switch e {
	case ListPartnerOrdersParamsStatusAccepted:
		return true
	case ListPartnerOrdersParamsStatusCancelled:
		return true
	case ListPartnerOrdersParamsStatusDelivered:
		return true
	case ListPartnerOrdersParamsStatusDelivering:
		return true
	case ListPartnerOrdersParamsStatusPendingConfirmation:
		return true
	case ListPartnerOrdersParamsStatusPreparing:
		return true
	case ListPartnerOrdersParamsStatusReady:
		return true
	case ListPartnerOrdersParamsStatusRejected:
		return true
	default:
		return false
	}
}

// AcceptOrderRequest defines model for AcceptOrderRequest.
type AcceptOrderRequest struct {
	EstimatedPreparationMinutes *int32 `json:"estimatedPreparationMinutes,omitempty"`

	// VenueOrderId Идентификатор заказа в системе заведения.
	VenueOrderId string `json:"venueOrderId"`
}

// CancelOrderRequest defines model for CancelOrderRequest.
type CancelOrderRequest struct {
	Reason *string `json:"reason,omitempty"`
}

// CreateOrderRequest defines model for CreateOrderRequest.
type CreateOrderRequest struct {
	CustomerComment *string          `json:"customerComment,omitempty"`
	DeliveryAddress DeliveryAddress  `json:"deliveryAddress"`
	Items           []OrderItemInput `json:"items"`

	// MenuVersion Версия меню, из которой пользователь собрал корзину.
	MenuVersion int64              `json:"menuVersion"`
	VenueId     openapi_types.UUID `json:"venueId"`
}

// DeliveryAddress defines model for DeliveryAddress.
type DeliveryAddress struct {
	AddressLine string  `json:"addressLine"`
	Apartment   *string `json:"apartment,omitempty"`
	City        string  `json:"city"`
	Comment     *string `json:"comment,omitempty"`
	Entrance    *string `json:"entrance,omitempty"`
	Floor       *string `json:"floor,omitempty"`
}

// HealthResponse defines model for HealthResponse.
type HealthResponse struct {
	// Service Example: platform
	Service string               `json:"service"`
	Status  HealthResponseStatus `json:"status"`

	// Version Example: 0.1.0
	Version *string `json:"version,omitempty"`
}

// HealthResponseStatus defines model for HealthResponse.Status.
type HealthResponseStatus string

// Menu defines model for Menu.
type Menu struct {
	Categories []MenuCategory     `json:"categories"`
	Currency   MenuCurrency       `json:"currency"`
	UpdatedAt  time.Time          `json:"updatedAt"`
	VenueId    openapi_types.UUID `json:"venueId"`
	Version    int64              `json:"version"`
}

// MenuCurrency defines model for Menu.Currency.
type MenuCurrency string

// MenuCategory defines model for MenuCategory.
type MenuCategory struct {
	Id        openapi_types.UUID `json:"id"`
	Items     []MenuItem         `json:"items"`
	Name      string             `json:"name"`
	SortOrder *int32             `json:"sortOrder,omitempty"`
}

// MenuCategoryInput defines model for MenuCategoryInput.
type MenuCategoryInput struct {
	ExternalCategoryId string          `json:"externalCategoryId"`
	Items              []MenuItemInput `json:"items"`
	Name               string          `json:"name"`
	SortOrder          *int32          `json:"sortOrder,omitempty"`
}

// MenuItem defines model for MenuItem.
type MenuItem struct {
	Available   bool    `json:"available"`
	Description *string `json:"description,omitempty"`

	// Id Стабильный публичный идентификатор товара платформы.
	Id        openapi_types.UUID `json:"id"`
	Name      string             `json:"name"`
	Price     Money              `json:"price"`
	SortOrder *int32             `json:"sortOrder,omitempty"`
	Tags      *[]string          `json:"tags,omitempty"`
}

// MenuItemInput defines model for MenuItemInput.
type MenuItemInput struct {
	Available   bool    `json:"available"`
	Description *string `json:"description,omitempty"`

	// ExternalItemId Идентификатор товара в системе заведения.
	ExternalItemId string    `json:"externalItemId"`
	Name           string    `json:"name"`
	Price          Money     `json:"price"`
	SortOrder      *int32    `json:"sortOrder,omitempty"`
	Tags           *[]string `json:"tags,omitempty"`
}

// MenuItemMapping defines model for MenuItemMapping.
type MenuItemMapping struct {
	ExternalItemId string             `json:"externalItemId"`
	ProductId      openapi_types.UUID `json:"productId"`
}

// MenuSyncRequest defines model for MenuSyncRequest.
type MenuSyncRequest struct {
	// Categories externalCategoryId и externalItemId должны быть уникальны в пределах снимка.
	Categories []MenuCategoryInput `json:"categories"`

	// MenuVersion Монотонно возрастающая версия меню в системе заведения.
	MenuVersion int64 `json:"menuVersion"`
}

// MenuSyncResponse defines model for MenuSyncResponse.
type MenuSyncResponse struct {
	AcceptedAt  time.Time          `json:"acceptedAt"`
	Items       []MenuItemMapping  `json:"items"`
	MenuVersion int64              `json:"menuVersion"`
	VenueId     openapi_types.UUID `json:"venueId"`
}

// Money defines model for Money.
type Money struct {
	// Amount Сумма в минимальных единицах валюты (для RUB — копейки).
	//
	// Example: 45900
	Amount   int64         `json:"amount"`
	Currency MoneyCurrency `json:"currency"`
}

// MoneyCurrency defines model for Money.Currency.
type MoneyCurrency string

// Order defines model for Order.
type Order struct {
	CreatedAt        time.Time          `json:"createdAt"`
	CustomerComment  *string            `json:"customerComment,omitempty"`
	DeliveryAddress  DeliveryAddress    `json:"deliveryAddress"`
	DeliveryFee      Money              `json:"deliveryFee"`
	EstimatedReadyAt *time.Time         `json:"estimatedReadyAt,omitempty"`
	Id               openapi_types.UUID `json:"id"`
	Items            []OrderItem        `json:"items"`

	// RejectionReason Заполняется platform только для заказа в статусе rejected.
	RejectionReason *string `json:"rejectionReason,omitempty"`

	// Status Жизненный цикл заказа: pending_confirmation → accepted → preparing →
	// ready → delivering → delivered. Из pending_confirmation также возможны
	// rejected и cancelled; из accepted возможен cancelled до начала приготовления.
	Status        OrderStatus          `json:"status"`
	StatusHistory *[]OrderStatusChange `json:"statusHistory,omitempty"`
	Subtotal      Money                `json:"subtotal"`
	Total         Money                `json:"total"`
	UpdatedAt     time.Time            `json:"updatedAt"`
	VenueId       openapi_types.UUID   `json:"venueId"`
	VenueName     string               `json:"venueName"`
}

// OrderEvent defines model for OrderEvent.
type OrderEvent struct {
	// EventId Стабильный ID события для дедупликации на стороне venue.
	EventId    openapi_types.UUID `json:"eventId"`
	OccurredAt time.Time          `json:"occurredAt"`
	Order      Order              `json:"order"`

	// Type Причина публикации нового снимка заказа в журнале заведения.
	Type OrderEventType `json:"type"`
}

// OrderEventPage defines model for OrderEventPage.
type OrderEventPage struct {
	Items []OrderEvent `json:"items"`

	// NextCursor Сохранить после применения событий страницы или постановки
	// временно неуспешных событий в локальную очередь повторов.
	NextCursor *string `json:"nextCursor,omitempty"`
}

// OrderEventType Причина публикации нового снимка заказа в журнале заведения.
type OrderEventType string

// OrderItem defines model for OrderItem.
type OrderItem struct {
	// Name Снимок названия на момент создания заказа.
	Name       string             `json:"name"`
	ProductId  openapi_types.UUID `json:"productId"`
	Quantity   int32              `json:"quantity"`
	TotalPrice Money              `json:"totalPrice"`
	UnitPrice  Money              `json:"unitPrice"`
}

// OrderItemInput defines model for OrderItemInput.
type OrderItemInput struct {
	ProductId openapi_types.UUID `json:"productId"`
	Quantity  int32              `json:"quantity"`
}

// OrderPage defines model for OrderPage.
type OrderPage struct {
	Items      []Order `json:"items"`
	NextCursor *string `json:"nextCursor,omitempty"`
}

// OrderStatus Жизненный цикл заказа: pending_confirmation → accepted → preparing →
// ready → delivering → delivered. Из pending_confirmation также возможны
// rejected и cancelled; из accepted возможен cancelled до начала приготовления.
type OrderStatus string

// OrderStatusChange defines model for OrderStatusChange.
type OrderStatusChange struct {
	ChangedAt time.Time               `json:"changedAt"`
	Reason    *string                 `json:"reason,omitempty"`
	Source    OrderStatusChangeSource `json:"source"`

	// Status Жизненный цикл заказа: pending_confirmation → accepted → preparing →
	// ready → delivering → delivered. Из pending_confirmation также возможны
	// rejected и cancelled; из accepted возможен cancelled до начала приготовления.
	Status OrderStatus `json:"status"`
}

// OrderStatusChangeSource defines model for OrderStatusChange.Source.
type OrderStatusChangeSource string

// ProblemDetails defines model for ProblemDetails.
type ProblemDetails struct {
	// Code Машиночитаемый код ошибки.
	//
	// Example: item_unavailable
	Code string `json:"code"`

	// Details Дополнительные поля ошибки, зависящие от `code`.
	Details *map[string]interface{} `json:"details,omitempty"`

	// Message Сообщение для журналов и отображения пользователю.
	Message string `json:"message"`
}

// RejectOrderRequest defines model for RejectOrderRequest.
type RejectOrderRequest struct {
	Comment *string                  `json:"comment,omitempty"`
	Reason  RejectOrderRequestReason `json:"reason"`
}

// RejectOrderRequestReason defines model for RejectOrderRequest.Reason.
type RejectOrderRequestReason string

// UpdateOrderStatusRequest defines model for UpdateOrderStatusRequest.
type UpdateOrderStatusRequest struct {
	Status UpdateOrderStatusRequestStatus `json:"status"`
}

// UpdateOrderStatusRequestStatus defines model for UpdateOrderStatusRequest.Status.
type UpdateOrderStatusRequestStatus string

// Venue defines model for Venue.
type Venue struct {
	Address     string             `json:"address"`
	City        string             `json:"city"`
	Id          openapi_types.UUID `json:"id"`
	IsOpen      bool               `json:"isOpen"`
	Kind        VenueKind          `json:"kind"`
	MenuVersion int64              `json:"menuVersion"`
	Name        string             `json:"name"`
	Status      VenueStatus        `json:"status"`
	UpdatedAt   time.Time          `json:"updatedAt"`
}

// VenueKind defines model for VenueKind.
type VenueKind string

// VenuePage defines model for VenuePage.
type VenuePage struct {
	Items []VenueSummary `json:"items"`

	// NextCursor Курсор следующей страницы; `null`, если страницы больше нет.
	NextCursor *string `json:"nextCursor,omitempty"`
}

// VenueStatus defines model for VenueStatus.
type VenueStatus string

// VenueSummary defines model for VenueSummary.
type VenueSummary struct {
	City string             `json:"city"`
	Id   openapi_types.UUID `json:"id"`

	// IsOpen Можно ли принять новый заказ прямо сейчас.
	IsOpen bool        `json:"isOpen"`
	Kind   VenueKind   `json:"kind"`
	Name   string      `json:"name"`
	Status VenueStatus `json:"status"`
}

// City defines model for City.
type City = string

// Cursor defines model for Cursor.
type Cursor = string

// IdempotencyKey defines model for IdempotencyKey.
type IdempotencyKey = string

// Limit defines model for Limit.
type Limit = int32

// OrderId defines model for OrderId.
type OrderId = openapi_types.UUID

// PartnerOrderStatus defines model for PartnerOrderStatus.
type PartnerOrderStatus string

// UserId defines model for UserId.
type UserId = string

// VenueId defines model for VenueId.
type VenueId = openapi_types.UUID

// BadRequest defines model for BadRequest.
type BadRequest = ProblemDetails

// InternalServerError defines model for InternalServerError.
type InternalServerError = ProblemDetails

// NotFound defines model for NotFound.
type NotFound = ProblemDetails

// Unauthorized defines model for Unauthorized.
type Unauthorized = ProblemDetails

// ListCustomerOrdersParams defines parameters for ListCustomerOrders.
type ListCustomerOrdersParams struct {
	// Limit Максимальное число элементов на странице.
	Limit *Limit `form:"limit,omitempty" json:"limit,omitempty"`

	// Cursor Непрозрачный курсор следующей страницы.
	Cursor *Cursor `form:"cursor,omitempty" json:"cursor,omitempty"`

	// XUserId Демонстрационный идентификатор пользователя; не является токеном авторизации.
	XUserId UserId `json:"X-User-Id"`
}

// CreateOrderParams defines parameters for CreateOrder.
type CreateOrderParams struct {
	// XUserId Демонстрационный идентификатор пользователя; не является токеном авторизации.
	XUserId UserId `json:"X-User-Id"`

	// IdempotencyKey Ключ повторяемой команды. Его область — субъект (`X-User-Id` или venue
	// API key) и конкретная операция. Повтор того же тела возвращает ранее
	// зафиксированный результат; тот же ключ с другим телом возвращает
	// `409 idempotency_key_reused`.
	IdempotencyKey IdempotencyKey `json:"Idempotency-Key"`
}

// GetCustomerOrderParams defines parameters for GetCustomerOrder.
type GetCustomerOrderParams struct {
	// XUserId Демонстрационный идентификатор пользователя; не является токеном авторизации.
	XUserId UserId `json:"X-User-Id"`
}

// CancelCustomerOrderParams defines parameters for CancelCustomerOrder.
type CancelCustomerOrderParams struct {
	// XUserId Демонстрационный идентификатор пользователя; не является токеном авторизации.
	XUserId UserId `json:"X-User-Id"`

	// IdempotencyKey Ключ повторяемой команды. Его область — субъект (`X-User-Id` или venue
	// API key) и конкретная операция. Повтор того же тела возвращает ранее
	// зафиксированный результат; тот же ключ с другим телом возвращает
	// `409 idempotency_key_reused`.
	IdempotencyKey IdempotencyKey `json:"Idempotency-Key"`
}

// ListVenuesParams defines parameters for ListVenues.
type ListVenuesParams struct {
	// City Фильтр по городу.
	City *City `form:"city,omitempty" json:"city,omitempty"`

	// Limit Максимальное число элементов на странице.
	Limit *Limit `form:"limit,omitempty" json:"limit,omitempty"`

	// Cursor Непрозрачный курсор следующей страницы.
	Cursor *Cursor `form:"cursor,omitempty" json:"cursor,omitempty"`
}

// ListPartnerOrderEventsParams defines parameters for ListPartnerOrderEvents.
type ListPartnerOrderEventsParams struct {
	// Cursor Непрозрачный курсор следующей страницы.
	Cursor *Cursor `form:"cursor,omitempty" json:"cursor,omitempty"`

	// Limit Максимальное число элементов на странице.
	Limit *Limit `form:"limit,omitempty" json:"limit,omitempty"`
}

// ListPartnerOrdersParams defines parameters for ListPartnerOrders.
type ListPartnerOrdersParams struct {
	// Status Фильтр по статусу; по умолчанию `pending_confirmation`.
	Status *ListPartnerOrdersParamsStatus `form:"status,omitempty" json:"status,omitempty"`

	// Limit Максимальное число элементов на странице.
	Limit *Limit `form:"limit,omitempty" json:"limit,omitempty"`

	// Cursor Непрозрачный курсор следующей страницы.
	Cursor *Cursor `form:"cursor,omitempty" json:"cursor,omitempty"`
}

// ListPartnerOrdersParamsStatus defines parameters for ListPartnerOrders.
type ListPartnerOrdersParamsStatus string

// AcceptPartnerOrderParams defines parameters for AcceptPartnerOrder.
type AcceptPartnerOrderParams struct {
	// IdempotencyKey Ключ повторяемой команды. Его область — субъект (`X-User-Id` или venue
	// API key) и конкретная операция. Повтор того же тела возвращает ранее
	// зафиксированный результат; тот же ключ с другим телом возвращает
	// `409 idempotency_key_reused`.
	IdempotencyKey IdempotencyKey `json:"Idempotency-Key"`
}

// RejectPartnerOrderParams defines parameters for RejectPartnerOrder.
type RejectPartnerOrderParams struct {
	// IdempotencyKey Ключ повторяемой команды. Его область — субъект (`X-User-Id` или venue
	// API key) и конкретная операция. Повтор того же тела возвращает ранее
	// зафиксированный результат; тот же ключ с другим телом возвращает
	// `409 idempotency_key_reused`.
	IdempotencyKey IdempotencyKey `json:"Idempotency-Key"`
}

// UpdatePartnerOrderStatusParams defines parameters for UpdatePartnerOrderStatus.
type UpdatePartnerOrderStatusParams struct {
	// IdempotencyKey Ключ повторяемой команды. Его область — субъект (`X-User-Id` или venue
	// API key) и конкретная операция. Повтор того же тела возвращает ранее
	// зафиксированный результат; тот же ключ с другим телом возвращает
	// `409 idempotency_key_reused`.
	IdempotencyKey IdempotencyKey `json:"Idempotency-Key"`
}

// CreateOrderJSONRequestBody defines body for CreateOrder for application/json ContentType.
type CreateOrderJSONRequestBody = CreateOrderRequest

// CancelCustomerOrderJSONRequestBody defines body for CancelCustomerOrder for application/json ContentType.
type CancelCustomerOrderJSONRequestBody = CancelOrderRequest

// SyncPartnerMenuJSONRequestBody defines body for SyncPartnerMenu for application/json ContentType.
type SyncPartnerMenuJSONRequestBody = MenuSyncRequest

// AcceptPartnerOrderJSONRequestBody defines body for AcceptPartnerOrder for application/json ContentType.
type AcceptPartnerOrderJSONRequestBody = AcceptOrderRequest

// RejectPartnerOrderJSONRequestBody defines body for RejectPartnerOrder for application/json ContentType.
type RejectPartnerOrderJSONRequestBody = RejectOrderRequest

// UpdatePartnerOrderStatusJSONRequestBody defines body for UpdatePartnerOrderStatus for application/json ContentType.
type UpdatePartnerOrderStatusJSONRequestBody = UpdateOrderStatusRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// ListCustomerOrders Получить заказы пользователя
	// (GET /api/v1/orders)
	ListCustomerOrders(w http.ResponseWriter, r *http.Request, params ListCustomerOrdersParams)
	// CreateOrder Создать заказ
	// (POST /api/v1/orders)
	CreateOrder(w http.ResponseWriter, r *http.Request, params CreateOrderParams)
	// GetCustomerOrder Получить заказ и его статус
	// (GET /api/v1/orders/{orderId})
	GetCustomerOrder(w http.ResponseWriter, r *http.Request, orderId OrderId, params GetCustomerOrderParams)
	// CancelCustomerOrder Отменить заказ
	// (POST /api/v1/orders/{orderId}/cancel)
	CancelCustomerOrder(w http.ResponseWriter, r *http.Request, orderId OrderId, params CancelCustomerOrderParams)
	// ListVenues Найти доступные заведения
	// (GET /api/v1/venues)
	ListVenues(w http.ResponseWriter, r *http.Request, params ListVenuesParams)
	// GetVenue Получить карточку заведения
	// (GET /api/v1/venues/{venueId})
	GetVenue(w http.ResponseWriter, r *http.Request, venueId VenueId)
	// GetVenueMenu Получить доступное меню заведения
	// (GET /api/v1/venues/{venueId}/menu)
	GetVenueMenu(w http.ResponseWriter, r *http.Request, venueId VenueId)
	// GetPlatformHealth Проверить готовность основного сервиса
	// (GET /healthz)
	GetPlatformHealth(w http.ResponseWriter, r *http.Request)
	// SyncPartnerMenu Синхронизировать снимок меню
	// (PUT /partner/v1/menu)
	SyncPartnerMenu(w http.ResponseWriter, r *http.Request)
	// ListPartnerOrderEvents Получить журнал изменений заказов заведения
	// (GET /partner/v1/order-events)
	ListPartnerOrderEvents(w http.ResponseWriter, r *http.Request, params ListPartnerOrderEventsParams)
	// ListPartnerOrders Получить заказы заведения для обработки
	// (GET /partner/v1/orders)
	ListPartnerOrders(w http.ResponseWriter, r *http.Request, params ListPartnerOrdersParams)
	// AcceptPartnerOrder Подтвердить заказ заведением
	// (POST /partner/v1/orders/{orderId}/accept)
	AcceptPartnerOrder(w http.ResponseWriter, r *http.Request, orderId OrderId, params AcceptPartnerOrderParams)
	// RejectPartnerOrder Отклонить заказ заведением
	// (POST /partner/v1/orders/{orderId}/reject)
	RejectPartnerOrder(w http.ResponseWriter, r *http.Request, orderId OrderId, params RejectPartnerOrderParams)
	// UpdatePartnerOrderStatus Обновить статус заказа
	// (POST /partner/v1/orders/{orderId}/status)
	UpdatePartnerOrderStatus(w http.ResponseWriter, r *http.Request, orderId OrderId, params UpdatePartnerOrderStatusParams)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// ListCustomerOrders operation middleware
func (siw *ServerInterfaceWrapper) ListCustomerOrders(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params ListCustomerOrdersParams

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: "int32"})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "limit"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "cursor" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "cursor", r.URL.Query(), &params.Cursor, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "cursor"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "cursor", Err: err})
		}
		return
	}

	headers := r.Header

	// ------------- Required header parameter "X-User-Id" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-User-Id")]; found {
		var XUserId UserId
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "X-User-Id", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-User-Id", valueList[0], &XUserId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "X-User-Id", Err: err})
			return
		}

		params.XUserId = XUserId

	} else {
		err := fmt.Errorf("Header parameter X-User-Id is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "X-User-Id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListCustomerOrders(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateOrder operation middleware
func (siw *ServerInterfaceWrapper) CreateOrder(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params CreateOrderParams

	headers := r.Header

	// ------------- Required header parameter "X-User-Id" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-User-Id")]; found {
		var XUserId UserId
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "X-User-Id", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-User-Id", valueList[0], &XUserId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "X-User-Id", Err: err})
			return
		}

		params.XUserId = XUserId

	} else {
		err := fmt.Errorf("Header parameter X-User-Id is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "X-User-Id", Err: err})
		return
	}

	// ------------- Required header parameter "Idempotency-Key" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Idempotency-Key")]; found {
		var IdempotencyKey IdempotencyKey
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "Idempotency-Key", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Idempotency-Key", valueList[0], &IdempotencyKey, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "Idempotency-Key", Err: err})
			return
		}

		params.IdempotencyKey = IdempotencyKey

	} else {
		err := fmt.Errorf("Header parameter Idempotency-Key is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "Idempotency-Key", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateOrder(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetCustomerOrder operation middleware
func (siw *ServerInterfaceWrapper) GetCustomerOrder(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "orderId" -------------
	var orderId OrderId

	err = runtime.BindStyledParameterWithOptions("simple", "orderId", r.PathValue("orderId"), &orderId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "orderId", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params GetCustomerOrderParams

	headers := r.Header

	// ------------- Required header parameter "X-User-Id" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-User-Id")]; found {
		var XUserId UserId
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "X-User-Id", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-User-Id", valueList[0], &XUserId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "X-User-Id", Err: err})
			return
		}

		params.XUserId = XUserId

	} else {
		err := fmt.Errorf("Header parameter X-User-Id is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "X-User-Id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetCustomerOrder(w, r, orderId, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CancelCustomerOrder operation middleware
func (siw *ServerInterfaceWrapper) CancelCustomerOrder(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "orderId" -------------
	var orderId OrderId

	err = runtime.BindStyledParameterWithOptions("simple", "orderId", r.PathValue("orderId"), &orderId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "orderId", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params CancelCustomerOrderParams

	headers := r.Header

	// ------------- Required header parameter "X-User-Id" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-User-Id")]; found {
		var XUserId UserId
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "X-User-Id", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-User-Id", valueList[0], &XUserId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "X-User-Id", Err: err})
			return
		}

		params.XUserId = XUserId

	} else {
		err := fmt.Errorf("Header parameter X-User-Id is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "X-User-Id", Err: err})
		return
	}

	// ------------- Required header parameter "Idempotency-Key" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Idempotency-Key")]; found {
		var IdempotencyKey IdempotencyKey
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "Idempotency-Key", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Idempotency-Key", valueList[0], &IdempotencyKey, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "Idempotency-Key", Err: err})
			return
		}

		params.IdempotencyKey = IdempotencyKey

	} else {
		err := fmt.Errorf("Header parameter Idempotency-Key is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "Idempotency-Key", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CancelCustomerOrder(w, r, orderId, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListVenues operation middleware
func (siw *ServerInterfaceWrapper) ListVenues(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params ListVenuesParams

	// ------------- Optional query parameter "city" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "city", r.URL.Query(), &params.City, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "city"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "city", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: "int32"})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "limit"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "cursor" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "cursor", r.URL.Query(), &params.Cursor, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "cursor"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "cursor", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListVenues(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetVenue operation middleware
func (siw *ServerInterfaceWrapper) GetVenue(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "venueId" -------------
	var venueId VenueId

	err = runtime.BindStyledParameterWithOptions("simple", "venueId", r.PathValue("venueId"), &venueId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "venueId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetVenue(w, r, venueId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetVenueMenu operation middleware
func (siw *ServerInterfaceWrapper) GetVenueMenu(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "venueId" -------------
	var venueId VenueId

	err = runtime.BindStyledParameterWithOptions("simple", "venueId", r.PathValue("venueId"), &venueId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "venueId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetVenueMenu(w, r, venueId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetPlatformHealth operation middleware
func (siw *ServerInterfaceWrapper) GetPlatformHealth(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetPlatformHealth(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// SyncPartnerMenu operation middleware
func (siw *ServerInterfaceWrapper) SyncPartnerMenu(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SyncPartnerMenu(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListPartnerOrderEvents operation middleware
func (siw *ServerInterfaceWrapper) ListPartnerOrderEvents(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params ListPartnerOrderEventsParams

	// ------------- Optional query parameter "cursor" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "cursor", r.URL.Query(), &params.Cursor, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "cursor"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "cursor", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: "int32"})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "limit"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListPartnerOrderEvents(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListPartnerOrders operation middleware
func (siw *ServerInterfaceWrapper) ListPartnerOrders(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params ListPartnerOrdersParams

	// ------------- Optional query parameter "status" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "status", r.URL.Query(), &params.Status, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "status"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "status", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: "int32"})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "limit"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "cursor" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "cursor", r.URL.Query(), &params.Cursor, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "cursor"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "cursor", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListPartnerOrders(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// AcceptPartnerOrder operation middleware
func (siw *ServerInterfaceWrapper) AcceptPartnerOrder(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "orderId" -------------
	var orderId OrderId

	err = runtime.BindStyledParameterWithOptions("simple", "orderId", r.PathValue("orderId"), &orderId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "orderId", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params AcceptPartnerOrderParams

	headers := r.Header

	// ------------- Required header parameter "Idempotency-Key" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Idempotency-Key")]; found {
		var IdempotencyKey IdempotencyKey
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "Idempotency-Key", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Idempotency-Key", valueList[0], &IdempotencyKey, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "Idempotency-Key", Err: err})
			return
		}

		params.IdempotencyKey = IdempotencyKey

	} else {
		err := fmt.Errorf("Header parameter Idempotency-Key is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "Idempotency-Key", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.AcceptPartnerOrder(w, r, orderId, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RejectPartnerOrder operation middleware
func (siw *ServerInterfaceWrapper) RejectPartnerOrder(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "orderId" -------------
	var orderId OrderId

	err = runtime.BindStyledParameterWithOptions("simple", "orderId", r.PathValue("orderId"), &orderId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "orderId", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params RejectPartnerOrderParams

	headers := r.Header

	// ------------- Required header parameter "Idempotency-Key" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Idempotency-Key")]; found {
		var IdempotencyKey IdempotencyKey
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "Idempotency-Key", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Idempotency-Key", valueList[0], &IdempotencyKey, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "Idempotency-Key", Err: err})
			return
		}

		params.IdempotencyKey = IdempotencyKey

	} else {
		err := fmt.Errorf("Header parameter Idempotency-Key is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "Idempotency-Key", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RejectPartnerOrder(w, r, orderId, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdatePartnerOrderStatus operation middleware
func (siw *ServerInterfaceWrapper) UpdatePartnerOrderStatus(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "orderId" -------------
	var orderId OrderId

	err = runtime.BindStyledParameterWithOptions("simple", "orderId", r.PathValue("orderId"), &orderId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "orderId", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params UpdatePartnerOrderStatusParams

	headers := r.Header

	// ------------- Required header parameter "Idempotency-Key" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Idempotency-Key")]; found {
		var IdempotencyKey IdempotencyKey
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "Idempotency-Key", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Idempotency-Key", valueList[0], &IdempotencyKey, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "Idempotency-Key", Err: err})
			return
		}

		params.IdempotencyKey = IdempotencyKey

	} else {
		err := fmt.Errorf("Header parameter Idempotency-Key is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "Idempotency-Key", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdatePartnerOrderStatus(w, r, orderId, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of [http.ServeMux].
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	http.Handler
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/healthz", wrapper.GetPlatformHealth)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/v1/venues", wrapper.ListVenues)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/v1/venues/{venueId}", wrapper.GetVenue)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/v1/venues/{venueId}/menu", wrapper.GetVenueMenu)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/v1/orders", wrapper.ListCustomerOrders)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/api/v1/orders", wrapper.CreateOrder)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/v1/orders/{orderId}", wrapper.GetCustomerOrder)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/api/v1/orders/{orderId}/cancel", wrapper.CancelCustomerOrder)
	m.HandleFunc(http.MethodPut+" "+options.BaseURL+"/partner/v1/menu", wrapper.SyncPartnerMenu)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/partner/v1/orders", wrapper.ListPartnerOrders)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/partner/v1/order-events", wrapper.ListPartnerOrderEvents)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/partner/v1/orders/{orderId}/accept", wrapper.AcceptPartnerOrder)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/partner/v1/orders/{orderId}/reject", wrapper.RejectPartnerOrder)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/partner/v1/orders/{orderId}/status", wrapper.UpdatePartnerOrderStatus)

	return m
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"7H3dchtHdv+rTM3/f7GbAkFKllMr6kqWvLvMWmuWtHalylAJI6AlzgqYgWcGirkqVpGEJVqhVoxVTtbl",
	"2HKc5DZVIMURhyABvkL3K/hJUn1OT0/3TONTJK2N1xcWQc7H6dPn/M5345Fd85st3yNeFNqLj+yWEzhN",
	"EpEAPl1zo1X+b52EtcBtRa7v2Ys2/W+a0CP2jG2ydYue0IFFX9EBW6cDus86Zbtku/yyT9skWLVLtuc0",
	"ib1o1/izSnZYWyFNhz+06Xz2AfHuRyv24oWFhZLddD35uWRHqy1+VxgFrnffXlsr2dfaQegHBnK+ozE9",
	"gdcfsHXaZVu0z7bpoUV7rMPW2QanzWIb9IjGnED2nD2lMT202AZfAe3SPk3YE7Y9lHJ8sUb7GFqX6qTZ",
	"8iPi1VZ/R0ws/IYesedsC9hH99gmp5Ht0Jge0wGQTgf0GEjbZ9tli/4rZ7FFB3SXHtEuUP7M+nH9K76I",
	"Dt1l/0xj2mOb1i+q/zj3UUiCuaV61eLbRBPrIfHapOJdXV6yHpDVX1o0wef3aY+t05ht0j7tsh3+9BMa",
	"Awuf0ITtlC36fUadxf9BKl7TmH+KOSkW3eOMp3tw31Pa5Q+0BFtjGlc8ekC77HOa0B7boAns0x78FXeJ",
	"k0APWAclinbZ5hV4FdvEF9GeYBXbsOg+W2cd+oom9DilYECPjTRUvOqlhcuWm+3EnQdk9U5A2iGpV8sV",
	"L93tFeLUSZBtt7J3c3zzSnZAPm27Aanbi1HQJsNk+OKvxsvwB27TjQzi8C3tIntg04/YM9qnA87lLZqA",
	"5A4s9mcQ4GMa0z5sxZ7F9y0nxTQeJsUNeLVKfJ3cc9qNyF68uFCy7/lB04nsRdv1oncu2iW+NLfZbmbK",
	"KT7JZbleRO6TANb1YVAnwVKdPxXe3XKilezVvvjrKE7K97fbLr+yyLtlJ4g8EsCrbkVO1A4ngSbOHi5U",
	"rMM15Yr4ZQf07IhtCb49t6ot4tVd7/6dmu/dczktru9VhzEzxPcbuWmbnmSXbOJx/n0y7M9OrUZaEeFr",
	"bwWk5cC6OcecOn9xnTTch0T8UnwgyNI/khreV3O8Gmk0SN2+bWIgxwXcoxzTvhK4009lies/AIQA0oTu",
	"C7FLUJM5RwEUAL+4vB6gWqNSsp0rXDhji+3QPf6RKyTbYDsIIj3+MFTcbgovNAGc4C9OysNUU2LbqSrl",
	"xxwfhwrvQ/HXNxHeNX5z2PK9kIDQvufUb5JP2yQELKj5XkQ8+NFptRpuDURi/o8h351Hymv+f0Du2Yv2",
	"/5vPbPY8/jWcXw78uw3SvE4ix22E+E6DneyBoVlHa5Fu7wHtogFlGzY3Xl5EAs9p3CLBQxK8HwRodc+L",
	"zBe0zzoghzFI4A6YJvYFTegulzxuyrmV2gNo7HKKf+9Hv/bbXv08yfwPGnNE4Q4GyjpHY3qImsKJ+shz",
	"2tGKH7h/IudK2EtQtQ78f5PusQ5YZOELgFHeA/7FtG9dXV6akwYW5GCPO0nA+YTtgHqIV3PKrgJGAQIr",
	"8uvU6y5/udNYDvwWCSKXS/k9pxESjmXZrx7ZJIzcphOR+jJAHHDghuu1I/zzcCN08dIYI1RCRVUMUY4t",
	"Xw/HML7uHu3yfy26Z4GbsgFIdsz3tcCWMlKmgUwRVjK4+ESnLQNn/y7Hbk78NYDuN+BsQBwhSApl73LT",
	"7bUbDedug6SwVaS0SE1AnIi8ATW1dhj5TRJc85tNIfO6uz+eLmnlVq/W6wEJw3GqcT13+VrJdiPShPvk",
	"D6MegPsTkeaS12oDH5rOZ0t4Z+oEpR8luU4QOKtwLfHaH5MgdHEXCqAWQyiScDBDH+55iSvlAfjiwgaC",
	"62+2qM+4WA7oLrh6R3jTOj2gCUdLLpCq7vz9JVvRloWh2oKKMt71Kogy2EN1xSmvi7tmkvbrxZ2dQrgc",
	"vOsD1yM5wXpnbBxZsp2WE0QGoXxnEpGsiYB4qti1xGNswxvfnUgLiBcFHBxmIfdew0fbPd2NuR0XkbvK",
	"dtOm/pY4jWjlpvBzptzTkAQPXVwk+cxptjhtdqvhRFw4bcPSQhkBpH61/8Dg9nJBlzqZPXmhfKG8MFbU",
	"My9fUGda9g3itadFRyci9/1AfJoIm/hbruFtgDZ59Km1g4BHrCpDbn70npEj7Vadm+Crkab8/Hdzkdsk",
	"tpGJk6KFxvCpMGkozjyUGCNXWVJ5qK5o2A5J3k23U+5kS57OznB6uB0x7SMGHbkYZjzAhH6AbpkWiZrC",
	"+jFch/UBEemqxnEUjeWUbuBnGGHIZ9SnjttmZbrBtgMOv20bYWDRhBsDojWlRX3ouMIgPEofetf3G8Tx",
	"7HyAobHk4mSenGtyyH9gm7RLdzFhk4aiJ6wDKc4ky+IOTz5gGox2uU/E/aYjSPR8Dp7RMeZzx6quYZ8v",
	"TmDRW4GwViNlzvfI6ptJRcmOnPu6lGsehIE0XZJH6DeuoaTs/iiRmkXPz1quUiUB+qYL+nTZmTHoGyMk",
	"PzPZyu3GjHJ2w2m1+NtmsyiZJBjY6tfbtWiWmKewsuxZw5Zya9WrzRg7a96hLtBFq2DRxNLJs+g+jyDp",
	"aw6gFt1l21AsYh0ux5DnEHjLxR7yfijlHD0fcz3oQxmiR7tluzS9dzoseJ4uXv4W0s8QF9M+/0nUeCA7",
	"jSn95+wplq32DLH1xCo93EW9MNZG6wGwsm+jhWKmACktD0zjtc/mIaUKuDZ2zwq8O4c0g8KHkY4QwOOU",
	"LG76bS8yeiodekyP0VDQY5oIFZGaxB5bIFeJKMJxRYIi5xF7zjbZtvULuk+P2I5186P3oGoL9dcTGtND",
	"2qPJL7kgyuD00ruXFxZMgqkU5MR/45I8k0eFOe4LVihPMDFZmp1p0A1Si1OJsSGZeA65w/QJvyaT22KZ",
	"3r5JnPrqiDVO6DGfcuApE5ygy6OSmVhUdH3vpkwr53TiL7SLmUraV8p7acYG3SuuHT0O3Sj8xTx7Vpql",
	"sZUWMnOO1rtFj2ks97Lk0Fh2iEqyvOm3bhiJPMHkPMWHXFtxvPvEhJth+27kR05jYkGa7uozT+h4bfL7",
	"WXxZU/Ch5nXS55ayVFuaRpYs0zUxZU1Rw0sKtIzLCMGmvf8wrcZN4Wbye5YmjWaXrqdJ+22IQHakJuxj",
	"KxLErBiVQOE76+gQ5YA+jbF9Z6JY1q8BXE8lCH6K4WOFPBPsCS4G5v6BX13wpQULxcM0qlNyRu/ZsnN/",
	"Wu9pBpxE8TCl6Mhn0dBetB/ogD2W7Tjc7+Yoic1n6Gwn6KKmPqgmIYamNFm4hceAkPUhcu3RpOJBy5No",
	"CkIvuU9jwNMTGrMvhG+SewV3Yo6gDSN1YDrcYR6wLVEX3hdky96MAd3DhqnpCgfD3bOcjBT5+D3nFNsC",
	"j6qrpIV0XRlAUPAK2nyysKVgaOhr1mHrUJ8/GhoIpP6RQBG9I8fYZJOi1p0aAH/dmGzPbO50EpvmDgry",
	"hcsc0B42HByIZjpAF+DVMbQOQtYDd/6A7meXKKzJGdrJUhOTx9Al+9O240WiYlYs7Y8s5gPKL0+VCGl7",
	"bjTNHTlhzZYmExeSfvXhGm1DZXvWjNlpMjiNFy5fniqqVRkhXzB0oecDxuNx+FSRaWh74b9Bm1pfdCZB",
	"++oTAKUjTbMWLVOTn/XjkxdWCirwQTb68U8VD3r94A9Zt5/6kdTLFv2aHpifDrahhz2z2A/LkQCyQPzR",
	"CGAWTSyJYFewAUGSpN0W0352JeSUAF+gZfIIMZkbs1ciSbMH3amIppWfvt1R20jhmE8ZqCKoT+NLzdyD",
	"U7JDvx2I8ndqh0TUyxmU1cHBGTSud4aYZ2i5G4kpKTwwqUquF21K9vp1Ym6Ehk6/PrgjCch0TI9FPz8d",
	"0H21FzDREieg1XfaXpZnNiYGxlCLG1TokB2k0S4QFUsvP04bdrQmxaSUehkJj4vZU5rwKwds06rylUNj",
	"cYGhTRKGAk6LbiW4cE9Rx/izRCShujbQE55YQiOxVei1dDSHNBY9L4/NxcFeZeSZZOEmqOWbdIy9QYtM",
	"pneyF6Qd3fHv3Qkjv/Yg1Zo7tYYfAnBEpLbiuTWncccNwzbEINGKFnYMYYR4kYkBH0HAqajXbGwotrVM",
	"gY63J2xoMdEPTdCzNWLN0IQ1Yx/VpFmx8MMW8cw1xwcutgmPAkngxe/4hRPkvEdnYGcsAU4G5kBnlsCa",
	"Og00ojYMbCrJoS2ZnUHOymawQnp+dN4lY6wi4AEJI6cdOJhvdu5hOsgPzGYOHnHmTidytt1sOuZ2q5E5",
	"gG+mGzu7YlU5wlVLFo3h8sSQBNhF7GZfYKN5zDbLpxiOq4Kk7IxTi9yHsB3tkLtxQzwtjVlTov454YCh",
	"uvga8yWYWwFXts92MGMDiYVsNAKceriI7XDnGAYQ6CH3hNmGYj3fBGXODydmVvqi4HACSK0duNHqLf4q",
	"3FMwtldbrnnwceyskTaN0GPrkLYSg4f7mAODxGm3OMQorjKmd4bMEwFr5q4uL4lRv1TRkXwYr3C9e35x",
	"IVeXlyxI7GEWKn35L1Jf/Ze5MRXpsHEvjP9GJqoUUulhKZe82pdZP8j4QZmRx3P8xwQaW2L6SrKRI4dV",
	"J01/rvDkmB6XK17Foy+g2EJPWIdt8qfsWezPwOFjbBzoQbETm2ZkypL7l/uAZK+545hf+THraMtlnbJV",
	"nXda7vzDC/N/V7V+XP+Kk4zPZOvsc9CfDeufyF0YPwH6+B+7Jas638JBv+xeTRbSprD8s4qbUfH0LSgp",
	"rfb4FK7kB2wbUmgxLmsTeyFkDl99hEm0LPoNSDPidQ9zbl0QcSDBuBsiV8ce84AG8sQb0MhgVUF55vwW",
	"8ZyWW151mo0qblv+LbAlx+kgj8z9WiAnoEHpmrqw0/kuqCcw9WiOCcBM0aSwPeWKp44Xw87sn/7soGGf",
	"rBsfL1c8MZ7M2dhlX0quZZuo2VhZQhngapA9J2IAOcZ5a3xI2RLDpRaotSJt2oQUl3ScZ9Y3c1FBLb6h",
	"fUijYLKkj2PbSpsNvhbLOhiuoQbDs7ZokkkjXxlf6hZXL62gGqNwqVhBj2lStgBf+6CnIjpNCVHCwIyJ",
	"zzPR01oSuuwxiN1yWs+FvU4EW7ewkyj9RYLNRIUibxqOJnI3Evz4WC/9DujeFcEOARS59+jJfTk9w57A",
	"T9tic7uibRS18mtIZKmFlhxlgv8og51MXRJ6UPGqv3n/D5YKRFCXmoPaVVjlKAs+AEzoAwd6IGVONNcg",
	"ThjN+V6NYBosciPITdwgTuOm344IlyilqT2dRVgr2ULr7UX7nfJC+R27BJOoYFNTLAUy4Df3iaFT5do/",
	"3BiqVbiFXK1SIH2mbQ1HgwSH6nusk2YsJM+wnZb7bpDBW6rbi/YHbhhdE2mqD5GyknaCxCdmvyS7ZF7M",
	"JK+Vxl6Jo/MTXCj88rXbuaHbiwsLpzaGmaW+TROYP2gT+d2c5PGtvoS0mF4haZ5XpoTXSva7k9xiGt0F",
	"Ny31zm040gEFXtQnlS0eKjx22iv6iZ1uuH17rWS3/HAmMTyBs0I2xSTqfkqKNtQGat2l++DebRRcobJF",
	"X+rnVYCLgfboBAQdzU5fFAHznY7V3EEPVTjvQushx7byrA4KYF6wIBVPc0z74udnBnehpHYrPle6FRMF",
	"zSRA58p3fGV6Aa/iwYEHfXlmBPRDKgQCYlaVEL0KXIWBb1D+Z7q/KbydBME03Tsgi21Y/DkVL1z1apmd",
	"O7SksKPZlOYf7e6uKDWnB38AUC5qgRXYZVF00GqWnIlongCU4QiHTWjZjukeD4UNpd89aBXFqjgyY0Tl",
	"+FDZDpogYOsQp0zCniG25Y6LQegCzX/Pr6+eGmoZxnrX9HgwCtpkrYCbF04XN42Y+RcpD6rQC//oNSi2",
	"MNA6drxWfWpD0DMj2l5auDT+FnnsANxw+TyH/L9XUUkPnAvn5GyAsiKzEqilHMuuEgih2eeoIOBzZvog",
	"4QnWd/Hiea7vP9PpDDyxQMXXmPZLhq3OJQzSFSKscmRIpEeYiDOUnp2mXf1BRS0F38ymc62U8+nmH4lT",
	"ctZm9+7SZKNi2cHFk6Wr2GxGCqj3G6L7dVNDX3rUwQTYl6Lkmbtro2FnJqU/e5/MwpzPq9xJRlML1TwW",
	"y6HFZEafjXtUQn8KRE7THWDRl/JJXfSdIBuFoeSxHMcaiNhkB+/jHpvxjCbOomraTlC9ojTcZRkDkWmB",
	"R1dlRa2K4b7pALMCMBYJwuPRRGuf2nPHHYuKl/GLbWd90bDaXcCuNBGgdefF+X41U87J5KfA9p670r49",
	"rk3x/JS14rlL54wpis6wL/FQoLfdr1DcsA62EvVFOvQAOxxyGCDdCJH+ktYmQxHuxeWCqNPEzpdDYWks",
	"SEIK6E2yKTKXb5kyvFkcl56uxaMcCJcg2y68K3Ne5WOkbVodhhM7/9qyKVlNd+JsilY0+YkzKt/RLj3E",
	"YoqWB0jzr/lDtSYTy/lHYlJi7fTSfTwEXhep1R7rYIZ5V3B3dP2s4CBiw8i08pmetXf28mSUpW9UBhhk",
	"ie28XX5gYcPeXJrmm+LAmhlFSooMThXLMXo4pvaF7krJ+oJevYAKFutk85N4nqx8UMVjG1ZVtvEtWlHQ",
	"JtUrxVCweGta5YFaRjetcWD+z3yuFpRiE/DYsDSFnXSvTF5WKvZw5s9bKfpAmUny/0XnOZwuq8X3b43M",
	"53KpCp1Tif8KHEf1p6GSTr9WXRU8JRFk9bpfe0AC6xpfT0gsfE5thdQeQDCmTc5gDnEfEqav0sxvWg4y",
	"wmZaUcPTsuwzFIXceVxG06rWtmWsVtghJZ8s9iiL65Rsd7EbIndSZ7ZXt1bDiDTFTillthSbxOCEAZuK",
	"fhYaOi3RKxScE6Vk2NUaoQYbMN+UOwvTULItln5pXLa0kRy2If1mZdaLO/+yDo0OM/4e+rn0LDR87GdC",
	"jzGiKAEA3l2peNixYaXFjCwvmqUEYaRLK5lw87FLY8C/E9oVm3XIw9j8WBrnjpZV72KHCDALiiCJbK4o",
	"1Apg3y2o9fd1PdELE/n0u2BZvuiR5EseBa26terVRP1eAPNZRJj5Qz0mypwvnMHrR+qzMh0mJV/pbps5",
	"G375fE8ANh3okcvIiHNtuaipNevjQqZGVgHON4P9bUp31nbCvoCT3HU9YJ03t6aiCQ+8EK397pPb3NvQ",
	"stRcEh6LzhiutfJEfvTnNgwipAC30LMicqsNEsNt7kvNRBxaLb/RcL37c6DemO8yo3wRns09M/q8dcUT",
	"dcokTXnnW+IsjG/RtdS/RCKm/bJ1nTT9OdEqko5U7AKvtoe/sw8oK6Y/kJuLlnFUVx8JTkRVM0afOZcX",
	"VHxa0R5kGOOFvOOoOd6sE0qpzKZnREOXMScg64GN8yPshW/N0CxgqeIB6w6tqmwFr8rzsUHo+Y95J0rG",
	"nQLm4WhcdKjWMwKxFswv6VmFYnBCD8sVT0QgYvKtWL/v4vS92knAX3ZCB2kXJDeT2U4P2CbIV88y9hbE",
	"IrlV8apirr1asnJvtYSWzKlf6gGr5YDFnnLvwNCMYDB0H7hhpH4LwvuobVPniERKZ+Is0ZmXZrKxfhOS",
	"/hewfJ3twMZtCQXqFmQR+xe0SfdJO4RntosXxt+inQN/jlBfCKy0qkKi98dpve6IE6NirdFmYIQBeCGC",
	"LuyP7WqjdIc566PTo1j5eFieyqJfcuhF51N8DUh6oEbabditePmKjzlNYa42XRHt0tzPx1pOXznh5kTG",
	"O1tZF7LSY6h0/wK8sse5ZUIH55HoD6b77EucUxAtzyjJsj1bda7B0OiWXbS7lGDBsilYS+NzsFPcwyFI",
	"XMzpg0BVtabISQBreqwyfOnLz6lX8OcKVVpPoqG0ItRNs9PclZkcopTSONaOx5TGh+QdcpNDSkl8z1Jc",
	"iI5su0MNPkkXKqBM9+O26WHFq6rfGVHVv4vL8MUtMhA61r82C0tNifa37JuziliY+/oua8y3d2UrNuk/",
	"fl+IqsNnWZQ+p1Kz4UtQ3oZScyHKn0Hf3/bq9HeY/1fbRcSx0WqbR87eqycoTdwzJzXkvGHQ0BWtgIqp",
	"wXEWyMNTNGaCPHCx8SwCoK9ksS3MRg5v6ZWH0EJIqXSjFVPkeJDA/zHIMJyOcM7pw4m7VXog9kq/yvl4",
	"Gn9Dnp8UeV5mO3+GqJNNK78x6lhpHtXQYwhDZvqc25Y2yyQGQnLVkXLFA2XIdRUrKJY+cU+ObWp80ovc",
	"e3g5+5LuL2o9hz8+eWFV4SSPKh77VM2O8xB/lUd6GKMqPGrEEBn99QPl0FNU3hq4/CFTcCsN/6GZ82+A",
	"+bMCTLnziaibqHKhII0ZKNfwO6VSPc3x7t/z0WAa6XEm9eyS3Q4a9qK9EkWtxfn5hl9zGit+GC3+auFX",
	"C6Ca4o2GY6SOsDzNqYfkPvHqLd/1onCi8r04NkFU7zlsFLRDjFuIYd/igP+oEUPxeNnIYXjB/9A+3ce+",
	"SxiH3x5Pd26cPC6O/Q85MSGjKN25tdtr/xsAAP//",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
